apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: online-oc
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: 2018-03-01T16:38:17Z
    creationTimestamp: null
    generation: 2
    name: online-oc
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
      from:
        kind: DockerImage
        name: docker.io/edseymour/gottyforocp:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
    - annotations:
      from:
        kind: DockerImage
        name: docker.io/edseymour/gottyforocp:v3.7
      generation: 2
      importPolicy: {}
      name: v3.7
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
    creationTimestamp: null
    generation: 1
    name: online-oc
  spec:
    replicas: 1
    selector:
      app: online-oc
      deploymentconfig: online-oc
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
        creationTimestamp: null
        labels:
          deploymentconfig: online-oc
      spec:
        containers:
        - name: oauth-proxy
          image: openshift/oauth-proxy:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8443
            name: public
          args:
          - --https-address=:8443
          - --provider=openshift
          - --openshift-service-account=online-oc
          - --upstream=http://localhost:8080
          - --tls-cert=/etc/tls/private/tls.crt
          - --tls-key=/etc/tls/private/tls.key
          - --cookie-secret=SECRET
          volumeMounts:
          - mountPath: /etc/tls/private
            name: proxy-tls
        - image: ''
          imagePullPolicy: Always
          name: online-oc
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        serviceAccountName: online-oc
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: proxy-tls
          secret:
            secretName: proxy-tls
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - online-oc
        from:
          kind: ImageStreamTag
          name: online-oc:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: proxy-tls
    creationTimestamp: null
    name: online-oc
  spec:
    ports:
    - name: proxy
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: online-oc
      deploymentconfig: online-oc
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: online-oc
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"online-oc"}}'
- apiVersion: v1
  kind: Route
  metadata:
    name: online-oc
  spec:
    port:
      targetPort: proxy
    tls:
      termination: Reencrypt
    to:
      kind: Service
      name: online-oc
      weight: 100
    wildcardPolicy: None
